name: KrabWidget
options:
  bundleIdPrefix: com.openclaw
  deploymentTarget:
    macOS: "14.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
  configs:
    Debug:
      DEBUG_INFORMATION_FORMAT: dwarf
    Release:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

targets:
  KrabWidget:
    type: application
    platform: macOS
    sources:
      - path: KrabWidget
        excludes:
          - "**/*.entitlements"
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: KrabWidget/Info.plist
        CODE_SIGN_ENTITLEMENTS: KrabWidget/KrabWidget.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.openclaw.krabwidget
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: KrabWidgetExtension
        embed: true
        codeSign: true
        buildPhase:
          copyFiles:
            destination: plugins

  KrabWidgetExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: KrabWidgetExtension
        excludes:
          - "**/*.entitlements"
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: KrabWidgetExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: KrabWidgetExtension/KrabWidgetExtension.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.openclaw.krabwidget.widget
        CODE_SIGN_STYLE: Automatic
        SKIP_INSTALL: YES
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
